export const itemJobs = [
	{
		imagen: 'screen-bfg-community.png',
		name: 'Beforget Community',
		texto:'Plataforma de comunidad y aprendizaje personalizada y replicable en base a Wordpress.',
		link:'https://www.beforget.community/',
		video: '',
		css_video:'',
		Api: 'BuddyBoss | Slack',
		Backend: 'Wordpress',
		front: 'Wordpress',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'bfg'	,
		date: '2021'
	},
	{
		imagen: 'screen-thairoom.jpg',
		name: 'Thai Room Spa',
		texto:'Desarrollo y gestón del sitio web en Worpdress.',
		link:'http://thairoomspa.com/',
		video: '',
		css_video:'',
		Api: '',
		Backend: 'Wordpress',
		front: 'Wordpress',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'wp',
		date: ''
	},
	{
		imagen: 'screen-weather.png',
		name: 'Weather App',
		texto:'Dashboard de gráficos con datos del clima de diferentes ciudades que se obtienen por medio de la API de Open Weather. Filtros, detalle, mapas, etc.',
		link:'https://weather-data-app.vercel.app/',
		video: '',
		css_video:'',
		Api: 'Open Weather Map | Redux',
		Backend: '',
		front: 'React',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'exp'	,
		date: '2020'
	},
	{
		imagen: 'screen-bfg.png',
		name: 'Beforget Sonrisa',
		texto:'Reconocimiento facial en el navegador web, el video se activa cuando reconocoe la sonrisa del usuario',
		link:'https://www.beforget.com/sonrisa/',
		video: '',
		css_video:'',
		Api: 'YouTube | Jeeliz',
		Backend: '',
		front: 'Vue',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'bfg'	,
		date: '2020'
	},
]