export const itemJobs = [
	{
		imagen: 'screen-bfg.png',
		name: 'Beforget Sonrisa',
		texto:'Siguiendo el concepto creativo de la marca y por medio de  reconocimiento facial en el navegador web, hicimos que el vídeo promocional se activará cuando la webcam detecta que el usuario ha sonreído.',
		link:'https://www.beforget.com/sonrisa/',
		video: '',
		css_video:'',
		Api: 'YouTube | Jeeliz',
		Backend: '',
		front: 'Vue',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'bfg'	
	},
	{
		imagen: 'screen-weather.png',
		name: 'Weather App',
		texto:'Aplicación experimental que a través de la API de Open Weather se obtienen los datos del clima de ciudades del mundo y se muestran en diferentes graficas. Tiene filtros, detalle, mapas, etc.',
		link:'https://weather-data-app.vercel.app/',
		video: '',
		css_video:'',
		Api: 'Open Weather Map | Redux',
		Backend: '',
		front: 'React',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'exp'	
	},
	{
		imagen: 'site-huawei.jpg',
		name: 'Huawei | Mate 8',
		texto:'Para lograr un sitio con dinamismo y movimiento utilizamos la librería TweenMax para animar tanto los elementos visuales de la marca como también las transiciones entre una sección y otra.',
		link:'https://nachodiaz8.com/hw-p8/',
		video: '',
		css_video:'no-video',
		Api: 'Youtube',
		Plug: 'fullPage.js',
		Backend: '',
		front: 'Vanilla JS - Jquery',
		Version: 'Escritorio',
		klass_mobile: 'none-mobile',
		Agencia: 'Raya',
		tipo: 'ag'
	},
	{
		imagen: 'screen-puma.png',
		name: 'Do You | Puma',
		texto:'Para que el sitio tuviese dinamismo con la librería ScrollMagic, logramos el efecto parallax al realizar el scroll de la página.',
		link:'https://nachodiaz8.com/doyou/',
		video: '',
		css_video:'no-video',
		Api: '',
		Backend: 'PHP - MySql',
		front: 'Vanilla JS - Jquery',
		Plug: 'ScrollMagic',
		Version: 'Escritorio - móvil',
		klass_mobile: '',
		Agencia: 'Raya',
		tipo: 'ag'
	},
	{
		imagen: 'screen-thairoom.jpg',
		name: 'Thai Room Spa',
		texto:'Creamos un cliente HTTP con las funcionalidades que nos entrega el Core de Wordpress para tener acceso a la API de Booker.com y crear los endpoint necesarios. De esa forma con un módulo en Vue que incorporamos en las páginas de los hoteles, mostramos el contenido tipo nombre, descripción, precio, etc de los servicios que disponen.',
		link:'http://thairoomspa.com/',
		video: '',
		css_video:'',
		Api: '',
		Backend: '',
		front: 'Vue',
		Plug: 'Axios',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'wp'
	},
	{
		imagen: 'screen-flateli.jpg',
		name: 'Flateli',
		texto:'Buscador de pisos de alquiler desarrollado en Wordpress y por medio de la WP REST API generamos diferentes endpoint para obtener la información solicitada, permitiendo desacoplar las vistas de la instalación de Wordpress.',
		link:'',
		video: '',
		css_video:'',
		Api: 'WP RESP API - Google Map - Fetch',
		front: 'Vanilla JS - Webpack',
		Backend: 'Wordpress',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'wp'
	},
	{
		imagen: 'screen-fgc.png',
		name: 'Familia de Galletas Costa',
		texto:'Para que el sitio tuviese transiciones fluidas y dinámicas entre una sección y otra usamos TweenMax, una librería de animación por Javascript, para así lograr ese dinamismo en los cambios visuales de contenidos.',
		link:'https://nachodiaz8.com/famila-costa/',
		video: '',
		css_video:'no-video',
		Api: '',
		Plug: 'MediaElementjs',
		front: 'Vanilla JS - Jquery',
		Backend: '',
		Version: 'Escritorio',
		klass_mobile: 'none-mobile',
		Agencia: 'Raya',
		tipo: 'a'
	},
	{
		imagen: 'screen-callao.png',
		name: 'Callao 28',
		texto:'Sitio desarrollado en Wordpress y la librería ScrollMagic para la animación.',
		link:'https://nachodiaz8.com/callao28',
		video: '',
		css_video:'',
		Api: '',
		front: 'Vanilla JS - Jquery',
		Backend: 'Wordpress',
		Plug: '',
		Version: 'Escritorio - móvil',
		Agencia: '',
		tipo: 'wp'
	},
	{
		imagen: 'screen-nomascuentos.png',
		name: 'No más cuentos | ABIF',
		texto:'Para que el sitio tuviese transiciones fluidas y dinámicas entre una sección y otra usamos TweenMax, una librería de animación por Javascript, para así lograr ese dinamismo en los cambios visuales de contenidos.',
		link:'https://nachodiaz8.com/nmc',
		video: '',
		css_video:'no-video',
		Api: 'Youtube',
		front: 'Vanilla JS - Jquery',
		Backend: '',
		Plug: 'SlickSlider',
		Version: 'Escritorio - móvil',
		klass_mobile: '',
		Agencia: 'Carcavilla Boutique',
		tipo: 'ag'
	}
]